# Generated by Django 5.1 on 2024-11-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('empaque',models.CharField(max_length=100)),
                ('contenido',models.CharField(max_length=100)),
                ('dir_cliente',models.CharField(max_length=100)),
                ('tel_cliente',models.CharField(max_length=100)),
                ('nom_cliente',models.CharField(max_length=100)),
                ('total',models.PositiveSmallIntegerField())

            ],
        ),
    ]
